trigger:
- master
- release/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: CmdLine@2
  inputs:
    script: './build.cmd Restore Compile --skip'
  displayName: 'Compile'
  condition: succeeded()

- task: CmdLine@2
  inputs:
    script: './build.cmd Test --skip'
  displayName: 'Test'
  condition: succeeded()

- task: CmdLine@2
  inputs:
    script: './build.cmd Pack UpdateBuildNumber --skip'
  displayName: 'Pack'
  condition: succeeded()

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: artifacts
    pathtoPublish: 'artifacts'
  displayName: 'Publish Build Artifacts'
  condition: succeeded()

- powershell: |
      $env:GIT_REDIRECT_STDERR = '2>&1'
      $envTag = "$(Build.BuildNumber)"
      $tag = $envTag.Substring(0, $envTag.lastIndexOf('.'))
      Write-Host "Release Tag = $tag"
      git tag $tag
      git tag
      git push --tags
  displayName: 'Tag Release branch'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
