trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
    - alpha/*
    - beta/*
jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'
  variables:
    cake.buildTarget: 'CI'
    build.configuration: 'Release'
    cake.verbosity: 'Verbose'
  steps:
  - checkout: self
    clean: true
  - powershell: ./build.ps1 -Target "$(cake.buildTarget)" -Configuration "$(build.configuration)" -Verbosity "$(cake.verbosity)"
    displayName: 'Cake Build'

  - powershell: Write-Host '##vso[build.addbuildtag]PR'
    displayName: 'Mark as PR Build'
    condition: and(succeeded(), in(variables['Build.Reason'], 'PullRequest'))

  - powershell: Write-Host '##vso[build.addbuildtag]Alpha'
    displayName: 'Mark as Alpha Build'
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/alpha/'))

  - powershell: Write-Host '##vso[build.addbuildtag]Beta'
    displayName: 'Mark as Beta Build'
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/beta/'))

  - powershell: Write-Host '##vso[build.addbuildtag]Release'
    displayName: 'Mark as Release Build'
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
