name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:


      - name: Checkout
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2


      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}


      - name: Fetch tags for GitVersion
        run: git fetch --prune --unshallow


      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'


      - name: Restore packages
        run: dotnet restore


      - name: Build
        run: dotnet build --configuration Release --no-restore


      - name: Test
        run: dotnet test --no-restore --verbosity normal


      - name: Generate NuGet packages
        run: dotnet pack src/GenericSearch/GenericSearch.csproj


      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./**/*.*pkg
