name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          config-file: ./.github/workflows/codeql-config.yml
          languages: 'csharp'

      - name: Fetch tags for GitVersion
        run: git fetch --prune --unshallow

      - name: Install .NET Core 3.1.x
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Restore packages
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal
            
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
      
      - name: Pack with dotnet
        run: dotnet pack src/GenericSearch/GenericSearch.csproj
          
      - uses: actions/upload-artifact@v2
        with:
          path: ./**/*.*pkg
