name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.2
        uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
        with: 
          nupkg-path:  './artifacts/*.*upkg'
          repo-owner: 'Grinderofl'
          gh-user: 'Grinderofl'
          token: ${{ secrets.NUGET_TOKEN }}
